spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
management:
  endpoint:
    web:
      exposure:
        include: "*"
  datasource:
    url:  jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
    ddl-auto: create;
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100




logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
  file:
    name: ./logs/data.log

